services:
  database:
    image: bitnami/postgresql
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - database:/bitnami/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - public_network

  server:
    build: .
    container_name: server
    image: backend-parking:0.1.0
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3500/api/v1/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - 3500:3500
    depends_on:
      - database
    networks:
      - public_network

volumes:
  database:

networks:
  public_network:
