services:
  database:
    image: bitnami/mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - database:/bitnami/mysql/data
      - ./db/mysql.init.sql:/docker-entrypoint-initdb.d/mysql.init.sql

  server:
    build: .
    container_name: server
    image: backend-parking:0.6.0
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3500/api/v1/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - 3500:3500
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    depends_on:
      - database

volumes:
  database:
